### ISSUE TITLE
Dracula plugin sets the color of labels

### ISSUE THREAD

**Issue by t1** [camunda/camunda-modeler-plugins#108]
__Describe the Bug__

When I edit a BPMN model with the Dracula plugin installed, it changes the color of all labels from:

```xml
<bpmndi:BPMNLabel>
```

to:

```xml
<bpmndi:BPMNLabel color:color="rgb(207, 205, 205)">
```

__Steps to Reproduce__

1. install Dracula plugin
2. open the Modeller
3. open a BPMN
4. change something
5. save
6. examine the updated BPMN

__Expected Behavior__

It should never change the color in the BPMN.

__Environment__

- OS: MacOS 14.4.1
- Camunda Modeler Version: 5.21.0

**Comment by nikku** [comment]
Please open the respective issue in the plug-in repository: https://github.com/hlucasfranca/camunda-modeler-plugin-dracula.
