### ISSUE TITLE
Images not found in Plugin

### ISSUE THREAD

**Issue by pme123** [camunda/camunda-modeler-plugins#12]
I tried to do the [camunda-modeler-plugin-example](https://github.com/camunda/camunda-modeler-plugin-example). 

I also tried [darlene](https://github.com/philippfromme/darlene).

In both examples the image is not found in the Modeler - the rest of the plugin seems to work.

![image](https://user-images.githubusercontent.com/3437927/47429029-502c9c80-d795-11e8-912d-39e41530bcaf.png)

**Comment by nikku** [comment]
Which platform are you on?

**Comment by pme123** [comment]
Mac OS, I am not sure if I was then already on Mojave.

**Comment by philippfromme** [comment]
The _Darlene_ plugin has been removed.

**Comment by nikku** [comment]
@barmac Could you check whether you're able to reproduce this issue?

**Comment by barmac** [comment]
I will.

**Comment by barmac** [comment]
I am able to reproduce this issue. 

I get the following error when logo.png is in the plugin directory: 
`Failed to load resource: net::ERR_FILE_NOT_FOUND`

Otherwise, it's:
`GET file:///Users/maciej.barelkowski/Desktop/Camunda%20Modeler%202.2.4.app/Contents/MacOS/plugins//camunda-modeler-plugin-example/logo.png 0 ()`

**Comment by nikku** [comment]
Does the file exist (on disk)?

**Comment by barmac** [comment]
The errors I pasted are shown in the following situations respectively
1. File is in the same directory as plugin (`~/Library/Application Support/camunda-modeler/plugins/camunda-modeler-plugin-example`).
2. There is no such file.

**Comment by nikku** [comment]
Further investigation showed that this is a general, not only OSX related issue. 

General steps to reproduce:

* Put plug-in into `${userData}/plugins` directory
* Resolving path fails

Requires fix via https://github.com/camunda/camunda-modeler/issues/1135.

**Comment by nikku** [comment]
Fixed via https://github.com/camunda/camunda-modeler/issues/1135.
