### ISSUE TITLE
Add custom translation plugin for i18n of the Camunda Modeler

### ISSUE THREAD

**Issue by philippfromme** [camunda/camunda-modeler-plugins#13]
There should be a ready-to-use-plugin for translating the Camunda Modeler.

__Tasks__

* [ ] Plug-in changes displayed text strings (UI)

**Comment by falko** [comment]
Good idea. It should use the i18n extension of the OMG BPMN Model Interchange Working Group: https://github.com/falko/bpmn-extensions/tree/master/i18n

**Comment by philippfromme** [comment]
@falko Sorry, I didn't make this clear enough. This issue is about i18n of the Camunda Modeler (menus, properties panel etc.).

**Comment by nikku** [comment]
@philippfromme: I updated the issue description, can you have a look if that is what you meant?

**Comment by philippfromme** [comment]
Yes, so this issue is about translating the Camunda Modeler application - not the diagrams.

**Comment by rob2universe** [comment]
https://github.com/FlowSquad/camunda-modeler-i18n-plugin

**Comment by nikku** [comment]
Already linked: https://github.com/camunda/camunda-modeler-plugins#plugins-in-other-repositories
