### ISSUE TITLE
some objects are not supported

### ISSUE THREAD

**Issue by ShMatin** [camunda/camunda-modeler-plugins#19]
Hi Philipp,

I'm a new user and I tried to use this plugin on a few BPMN diagrams. After I run the simulation I receive ''Not Supported'' message on some of the objects. Do they need a specific configuration? 
What is the minimum configuration required for them to run?

Thanks!
Shahab

**Comment by philippfromme** [comment]
> this plugin

Which plugin are you referring to?

**Comment by ShMatin** [comment]
token simulation for Camunda

**Comment by ShMatin** [comment]
''Not Supported'' message appears on message flows and send message events. I Know tokens don't go through message flows but I have to delete all the ''Not Supported'' objects every time.

**Comment by ShMatin** [comment]
attached are two examples, Thank you.


![IMG-2032 - Kopie - Kopie](https://user-images.githubusercontent.com/20598789/71730794-6925e880-2e43-11ea-975d-2a33c2410081.jpg)
![IMG-2032 - Kopie](https://user-images.githubusercontent.com/20598789/71730813-793dc800-2e43-11ea-988b-6a57b0de2bce.jpg)

**Comment by philippfromme** [comment]
As you can see, message flows and certain other elements are not supported by this plugin. I don't think there will be support anytime soon as the token simulation is focussed on simple scenarios.
