### ISSUE TITLE
TX Plugin: TX boundaries are displayed on associations

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler-plugins#3]
![2017-07-05 - seleccion 001](https://user-images.githubusercontent.com/40038/27869872-9074d5ca-61a1-11e7-9c03-d8e64ef6db18.png)

**Comment by joehm** [comment]
The same applies to message and data flows! Async before is shown for incoming, async after for outgoing message/data flows.
<img width="864" alt="bildschirmfoto 2017-07-26 um 12 44 56" src="https://user-images.githubusercontent.com/4679403/28617495-c4cb9060-7200-11e7-845b-cc251aace1ec.png">

**Comment by falko** [comment]
The easiest would probably be, to take my original code from the Process Test Coverage project, which also uses the traditional red lines that we are drawing on white boards since a decade: https://github.com/camunda/camunda-bpm-process-test-coverage/blob/master/core/src/main/resources/bpmn.js-report-template.html

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler-plugins/commit/66a6978a3e061caeb25a7b678a30b42366d70ce6.
