### ISSUE TITLE
Fix compatibility with Modeler v4.6

### ISSUE THREAD

**Issue by rob2universe** [camunda/camunda-modeler-plugins#35]
Still working on 4.5, on 4.6:

> Cannot read property '$type' of undefined
>     at TransactionBoundaries../node_modules/camunda-transaction-boundaries/lib/TransactionBoundaries.js.TransactionBoundaries._getTransactionBoundaries (webpack:///node_modules/camunda-transaction-boundaries/lib/TransactionBoundaries.js:67:0)
>     at file:///C:/Users/Rob/AppData/Roaming/camunda-modeler/resources/plugins/camunda-transaction-boundaries-plugin/client/client-bundle.js:387:38
>     at file:///C:/tools/camunda-modeler/resources/app.asar/public/2.2.js:1:14123
>     at Array.forEach (<anonymous>)
>     at forEach (webpack:///node_modules/diagram-js/lib/core/ElementRegistry.js:181:19)
>     at TransactionBoundaries../node_modules/camunda-transaction-boundaries/lib/TransactionBoundaries.js.TransactionBoundaries._getTransactionBoundaryElements (webpack:///node_modules/camunda-transaction-boundaries/lib/TransactionBoundaries.js:105:0)
>     at TransactionBoundaries../node_modules/camunda-transaction-boundaries/lib/TransactionBoundaries.js.TransactionBoundaries.show (webpack:///node_modules/camunda-transaction-boundaries/lib/TransactionBoundaries.js:204:0)
>     at TransactionBoundaries../node_modules/camunda-transaction-boundaries/lib/TransactionBoundaries.js.TransactionBoundaries.toggle (webpack:///node_modules/camunda-transaction-boundaries/lib/TransactionBoundaries.js:280:0)
>     at Object.toggleTransactionBoundaries (webpack:///client/module.js:9:0)
>     at opts (webpack:///node_modules/diagram-js/lib/features/editor-actions/EditorActions.js:170:31) [ error ]
> This error may be the result of a plug-in compatibility issue. [ info ]
> Disable plug-ins (restarts the app) [ info ]

**Comment by pinussilvestrus** [comment]
Seems like we had a change [that `eventDefinitions` are not undefined per default](https://github.com/bpmn-io/camunda-transaction-boundaries/blob/master/lib/TransactionBoundaries.js#L67), but an empty array for some elements.

I'll have a look.

**Comment by pinussilvestrus** [comment]
Related sentry issue: https://sentry.io/organizations/camunda-modeling/issues/2219558353/?project=5223041&query=is%3Aunresolved

**Comment by pinussilvestrus** [comment]
This will be fixed by https://github.com/bpmn-io/camunda-transaction-boundaries/pull/12 (Merged + Released + Integrated). We should ensure the plugins is able to deal with those cases.

Furthermore, I pushed a fix to `@bpmn-io/extract-process-variables` (https://github.com/bpmn-io/extract-process-variables/pull/12) to ensure we do not accidentally override properties.
