### ISSUE TITLE
TX Plugin: asyncBefore=true on Start Event is not displayed

### ISSUE THREAD

**Issue by falko** [camunda/camunda-modeler-plugins#4]
maybe because there is no Sequence Flow?

**Comment by falko** [comment]
![2017-07-05 - seleccion 001](https://user-images.githubusercontent.com/40038/27869956-c88be37c-61a1-11e7-9dc4-7c0450a9aee0.png)

**Comment by nikku** [comment]
Closed via https://github.com/camunda/camunda-modeler-plugins/commit/66a6978a3e061caeb25a7b678a30b42366d70ce6.
