### ISSUE TITLE
Link to documentation -> 404

### ISSUE THREAD

**Issue by franzheidl** [camunda/camunda-modeler-plugins#6]
The link to further docs (points to https://github.com/camunda/camunda-modeler/tree/547-plugins/docs/plugins) in the last line of the RM at https://github.com/camunda/camunda-modeler-plugins/blob/master/bpmn-js-plugin-example/README.md gives a 404.

**Comment by franzheidl** [comment]
I presume this is meant to point at https://github.com/camunda/camunda-modeler/tree/master/docs/plugins? If anyone can confirm I 'm happy to fix, @philippfromme 👍

**Comment by mburke84** [comment]
@franzheidl, yepp that's where the link should point to. Or at least it did when I used it last a few weeks ago.

Cheers

**Comment by franzheidl** [comment]
OK, I'll fix.

**Comment by franzheidl** [comment]
Fixed.
