### ISSUE TITLE
Please add an example to integrate a custom properties provider

### ISSUE THREAD

**Issue by Ichigo85** [camunda/camunda-modeler-plugins#65]
Hi! I am working on my plugins, compatible to Camunda Modeler 4.x, to make them working on Camunda Modeler 5.x. I found really helpful the autosave plugin and the bpmn-js properties-panel-extension example to start, but they use two different aliases for react in their webpack configuration. 
Now, if I use the 'camunda-modeler-plugin-helpers/react' alias, the plugin works without errors but the "useService" function does not work.
If I change the alias to preact-compat, I have this error
`Invariant Violation: Minified React error #284;`

I think that a new camunda modeler plugin example to integrate a custom properties panel would be really helpful to understand the potential of your new major update.
Also, some help would really be appreciated 😉 Thank you!

**Comment by pinussilvestrus** [comment]
Hi! There is already a plugin that extends the properties panel: https://github.com/camunda/camunda-modeler-process-io-specification-plugin

Would this already help as a starter?

**Comment by Ichigo85** [comment]
Hi @pinussilvestrus ! Yes, that could probably help! I will try to adapt my plugin to that properties panel, let's see if that's the key :)

**Comment by Ichigo85** [comment]
Hello @pinussilvestrus! Using your plugin as a starter, I could fix mine! Thank you!
