### ISSUE TITLE
Properties Panel and Moddle not working

### ISSUE THREAD

**Issue by billbarni** [camunda/camunda-modeler-plugins#67]
The logging project is not working
The moddle project is not working...

Alpha versions of some packages give problems. Many of the compilations are not captured.

Many plugins that work are only loaded in Camunda 7 bpms, not in Camunda 8.

**Comment by pinussilvestrus** [comment]
Hi @billbarni, could you maybe use [our issue templates](https://github.com/camunda/camunda-modeler-plugins/issues/new?assignees=&labels=bug&template=BUG_REPORT.md) to provide some more details? Especially interesting would be which Camunda Modeler version are you using.

Note that the issue templates were missing for this project and were just added; sorry for that.

**Comment by pinussilvestrus** [comment]
Any updates on this one @billbarni ?
