### ISSUE TITLE
bpmn-js-plugin-embedded-comments: comments not persitent

### ISSUE THREAD

**Issue by traumatic** [camunda/camunda-modeler-plugins#7]
Hi,

To my understanding the 'bpmn-js-embedded-comments' project supports writing comments into the bpmn:documentation tag and makes them persistent. I.e. once the process model is saved the comments are too. 
But when I use the plugin 'bpmn-js-plugin-embedded-comments' in my modeler, comments are not made persistent. Next time I open the model all comments are gone.

Is this a bug in the plugin?

**Comment by nikku** [comment]
![image](https://user-images.githubusercontent.com/58601/50970330-68cd6880-14e1-11e9-842c-10cbb9728551.png)

Comments are persisted, you need to save them by pressing `ENTER` though.
